-- 방문 목적(purpose)별 총 방문 횟수를 가져오는 쿼리를 작성해주세요. 출력 결과는 방문 목적(purpose), 총 방문 횟수 순서로 select 되어야 합니다.
-- 출력 예시
-- purpose	         total
-- work	           	  18
-- visit family	       1 
-- ...                ...